name: Trigger auto deployment for containerapp cloudextend-admin

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/src/Skoruba.Duende.IdentityServer.Admin/**'
    - '.github/workflows/cloudextend-admin-AutoDeployTrigger-6e2be401-e70b-43cd-91b5-9c4d2acfb6b9.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cloudextend.azurecr.io
          username: ${{ secrets.CLOUDEXTENDADMIN_REGISTRY_USERNAME }}
          password: ${{ secrets.CLOUDEXTENDADMIN_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cloudextend.azurecr.io/cloudextend-admin:${{ github.sha }}
          file: /src/Skoruba.Duende.IdentityServer.Admin/Dockerfile
          context: /src/Skoruba.Duende.IdentityServer.Admin/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CLOUDEXTENDADMIN_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n cloudextend-admin -g cloudextend-prod --server cloudextend.azurecr.io --username  ${{ secrets.CLOUDEXTENDADMIN_REGISTRY_USERNAME }} --password ${{ secrets.CLOUDEXTENDADMIN_REGISTRY_PASSWORD }}
            az containerapp update -n cloudextend-admin -g cloudextend-prod --image cloudextend.azurecr.io/cloudextend-admin:${{ github.sha }}
